/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package busticketbooking;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Dristy
 */
public class SeatReservation extends javax.swing.JFrame {
  Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    String ob;String bid;
    
    
    /**
     * Creates new form SeatReservation
     */
    
    public SeatReservation() throws SQLException {
        super("Booking");
        initComponents();
        conn = JavaConnect.ConnecrDb();
    this.bid=bid;
    }
 
 public void setBid(String x)
 {
 this.bid=x;
 }
 public String getBid()
 {
 return bid;
 }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        comboboxSelectBus_booking = new javax.swing.JComboBox<>();
        comboboxBusType_booking = new javax.swing.JComboBox<>();
        comboboxFrom_booking = new javax.swing.JComboBox<>();
        comboboxTo_booking = new javax.swing.JComboBox<>();
        etDate_booking = new javax.swing.JTextField();
        etTime_booking = new javax.swing.JTextField();
        btnSubmit_booking = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Select Bus");

        jLabel2.setText("Selct Type");

        jLabel3.setText("From");

        jLabel4.setText("To");

        jLabel5.setText("Date");

        jLabel6.setText("Time");

        comboboxSelectBus_booking.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Bus", "Welcome", "Khulna", "Borisal", "Vola", "Feni" }));

        comboboxBusType_booking.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Type", "AC", "Non_AC" }));

        comboboxFrom_booking.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "From", "Dhaka", "Khulna", "Vola", "Feni", "Borisal" }));

        comboboxTo_booking.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Destination", "Dhaka", "Khulna", "Vola", "Feni" }));

        etDate_booking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etDate_bookingActionPerformed(evt);
            }
        });

        etTime_booking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etTime_bookingActionPerformed(evt);
            }
        });

        btnSubmit_booking.setText("Submit");
        btnSubmit_booking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmit_bookingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboboxBusType_booking, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboboxTo_booking, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboboxSelectBus_booking, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboboxFrom_booking, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etDate_booking)
                    .addComponent(etTime_booking))
                .addContainerGap(160, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSubmit_booking)
                .addGap(78, 78, 78))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(comboboxSelectBus_booking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboboxBusType_booking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboboxFrom_booking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboboxTo_booking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(etDate_booking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(etTime_booking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnSubmit_booking)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmit_bookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmit_bookingActionPerformed
        // TODO add your handling code here:
         String sql = "select * from BusInformation where Bname=? and Btype=? and FromRoute=? and ToRoute=? and Date=? and Time=?";
        try {
            pst = conn.prepareStatement(sql);

            String bname = (String) comboboxSelectBus_booking.getSelectedItem();
            String btype = (String) comboboxBusType_booking.getSelectedItem();
            String from = (String) comboboxFrom_booking.getSelectedItem();
            String to = (String) comboboxTo_booking.getSelectedItem();
            String date = etDate_booking.getText();
            String time = etTime_booking.getText();
            
           
             boolean isDate = false;
            boolean isTime1 = false;
            boolean isTime2 = false;
         String datePattern = "\\d{1,2}-\\d{1,2}-\\d{4}";
         String timePattern1 = "\\d{1,2}:\\d{1,2}am";
         String timePattern2 = "\\d{1,2}:\\d{1,2}pm";
      isDate = date.matches(datePattern);
      if(isDate==false)
      {
      JOptionPane.showMessageDialog(null, "Date in wrong format");
      }
     isTime1= time.matches(timePattern1);
     isTime2= time.matches(timePattern2);
      if((isTime1==false)&&(isTime2==false))
      {
      JOptionPane.showMessageDialog(null, "Time in wrong format");
      }
       pst.setString(1, bname);
            pst.setString(2, btype);
            pst.setString(3, from);
            pst.setString(4, to);
            pst.setString(5, date);
            pst.setString(6, time);
            rs = pst.executeQuery();
            BookReservation home = null;
int flag=0; 
                if(rs.next()) {
                    ob=rs.getString("BID");
                    setBid(ob);
                    setVisible(false);
                    home = new BookReservation();
                    home.setVisible(true);
                    rs.close();
                    pst.close();
                     flag=1;
     
                   
                }
                else {
                    JOptionPane.showMessageDialog(null, "There is no bus available");
                }
                 

         
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {

            }
        }

    }//GEN-LAST:event_btnSubmit_bookingActionPerformed

    private void etDate_bookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etDate_bookingActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_etDate_bookingActionPerformed

    private void etTime_bookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etTime_bookingActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_etTime_bookingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeatReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeatReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeatReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeatReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new SeatReservation().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(SeatReservation.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit_booking;
    private javax.swing.JComboBox<String> comboboxBusType_booking;
    private javax.swing.JComboBox<String> comboboxFrom_booking;
    private javax.swing.JComboBox<String> comboboxSelectBus_booking;
    private javax.swing.JComboBox<String> comboboxTo_booking;
    private javax.swing.JTextField etDate_booking;
    private javax.swing.JTextField etTime_booking;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
