
package busticketbooking;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Date;

        


public class Admin extends javax.swing.JFrame {
    

    Connection conn;
    ResultSet rs,rs1;
    PreparedStatement pst, pst2,pst3;
    
  /*  public void clock(){
        
        Thread clock=new Thread()
        {
            public void run()
            {
               try {
                   Calendar cal= new GregorianCalendar();
                   int day=cal.get (Calendar.DAY_OF_MONTH);
                   int month=cal.get (Calendar.MONTH);
                   int year=cal.get (Calendar.YEAR);
                   
                   int second=cal.get (Calendar.SECOND);
                   int minute=cal.get (Calendar.MINUTE);
                   int hour=cal.get (Calendar.HOUR);
                   ettttt.setText("Time :"+hour+":"minute+":"+second+"  Date :"+year+"-"+month+"-"+day);
                   sleep(1000);
                   
               } catch(InterruptedException e){
                   e.printStackTrace();
               }
            }
        };
        clock.start();
    }*/
    public Admin() throws SQLException {
        initComponents();
        conn = JavaConnect.ConnecrDb();
        updateTable();
        etTotalSeat_dashboard.setText(Integer.toString(getTotalSeat()));
        etAvailableSeat_dashboard.setText(Integer.toString(getAvailableSeat()));
        showTime();
        showDate();
    }
    public int getTotalSeat()
    {
       
        int rowsCount=tblBusInfo_dashboard.getRowCount();
        int i_sum=0;
        for(int i=0;i<rowsCount;i++)
        {
           i_sum=i_sum+Integer.parseInt(tblBusInfo_dashboard.getValueAt(i,7).toString());
        }
        return i_sum;
    }
    public int getAvailableSeat()
    {
       
        int i_rowsCount=tblBusInfo_dashboard.getRowCount();
        int i_sum=0;
        for(int i=0;i<i_rowsCount;i++)
        {
           i_sum=i_sum+Integer.parseInt(tblBusInfo_dashboard.getValueAt(i,8).toString());
        }
        return i_sum;
    }
    private void updateTable()
    {
        
        try{
            String sql="select bid,bname,btype,bfrom,bto,bdeparturetime,barrival,btotalseat,bavailable from busscheduling ";
            String sql2="select uid,noofseat from booking_information ";
            pst=conn.prepareStatement(sql);
            pst3=conn.prepareStatement(sql2);
            
            rs=pst.executeQuery();
            rs1=pst3.executeQuery();
            tblBusInfo_dashboard.setModel(DbUtils.resultSetToTableModel(rs));
            tblBooking_Dashboard.setModel(DbUtils.resultSetToTableModel(rs1));
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    void showDate()
    {
        Date d =new Date();
        SimpleDateFormat s= new SimpleDateFormat("YYYY-MM-dd");
        lblDate_dashboard.setText(s.format(d));
       
        
    }
    
    void showTime()
    {
       new Timer(0,new ActionListener(){
           
       public void actionPerformed(ActionEvent e)
        {
            Date d =new Date();
             SimpleDateFormat s= new SimpleDateFormat("hh:mm:ss a");  
               lblTime_dashboard.setText(s.format(d));
                       }
        }).start();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        etBusId_busScheduling = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnAdd_busScheduling = new javax.swing.JButton();
        btnDelete_busScheduling = new javax.swing.JButton();
        btnSearch_busScheduling = new javax.swing.JButton();
        btnModify_busScheduling = new javax.swing.JButton();
        btnClear_busScheduling = new javax.swing.JButton();
        etDate_busScheduling = new javax.swing.JTextField();
        etFare_busScheduling = new javax.swing.JTextField();
        etavailableSeat_busScheduling = new javax.swing.JTextField();
        etTotalSeat_busScheduling = new javax.swing.JTextField();
        etArrival_busScheduling = new javax.swing.JTextField();
        etDeparture_busScheduling = new javax.swing.JTextField();
        etTo_busScheduling = new javax.swing.JTextField();
        etFrom_busScheduling = new javax.swing.JTextField();
        etBusType_busScheduling = new javax.swing.JTextField();
        etBusName_busScheduling = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBusInfo_dashboard = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBooking_Dashboard = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        etTotalSeat_dashboard = new javax.swing.JTextField();
        lblDate_dashboard = new javax.swing.JLabel();
        etAvailableSeat_dashboard = new javax.swing.JTextField();
        lblTime_dashboard = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btnRefresh_dashboard = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel13.setText("Bus Scheduling");

        jLabel1.setText("Bus Id : ");

        jLabel2.setText("Bus Name :");

        jLabel3.setText("Bus Type  :");

        jLabel4.setText("From  :");

        jLabel11.setText("To     :");

        jLabel6.setText("Departure :");

        jLabel7.setText("Arrival :");

        jLabel8.setText("Total Seat :");

        jLabel9.setText("Available Seat :");

        jLabel10.setText("Fare  :");

        jLabel12.setText("Date");

        btnAdd_busScheduling.setText("Add");
        btnAdd_busScheduling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd_busSchedulingaddBusScheduling(evt);
            }
        });

        btnDelete_busScheduling.setText("Delete");
        btnDelete_busScheduling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete_busSchedulingdeleteBusSchedule(evt);
            }
        });

        btnSearch_busScheduling.setText("Search");
        btnSearch_busScheduling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch_busSchedulingsearchBusSchedule(evt);
            }
        });

        btnModify_busScheduling.setText("Modify");
        btnModify_busScheduling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModify_busSchedulingmodifyBusSchedule(evt);
            }
        });

        btnClear_busScheduling.setText("Clear");
        btnClear_busScheduling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear_busSchedulingclearBusSchedule(evt);
            }
        });

        etBusName_busScheduling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etBusName_busSchedulingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnAdd_busScheduling)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete_busScheduling)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etBusName_busScheduling, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etBusId_busScheduling, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(etDate_busScheduling, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(etTo_busScheduling, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(etArrival_busScheduling, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(etavailableSeat_busScheduling, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(etFare_busScheduling, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(etTotalSeat_busScheduling, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(etDeparture_busScheduling, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(etFrom_busScheduling, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(etBusType_busScheduling, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSearch_busScheduling, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModify_busScheduling)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClear_busScheduling)))
                .addContainerGap(171, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(280, 280, 280))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(etBusId_busScheduling, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(etBusName_busScheduling, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(etBusType_busScheduling, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etFrom_busScheduling, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etTo_busScheduling, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(etDeparture_busScheduling, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(etArrival_busScheduling, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(etTotalSeat_busScheduling, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(etavailableSeat_busScheduling, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(etFare_busScheduling, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(etDate_busScheduling, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd_busScheduling)
                    .addComponent(btnDelete_busScheduling)
                    .addComponent(btnModify_busScheduling)
                    .addComponent(btnClear_busScheduling)
                    .addComponent(btnSearch_busScheduling))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Bus Scheduling", jPanel1);

        tblBusInfo_dashboard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblBusInfo_dashboard);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("DashBoard");

        tblBooking_Dashboard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblBooking_Dashboard);

        jLabel14.setText("Bus Information :");

        jLabel15.setText("Booking Information :");

        jLabel16.setText("Total Seat :");

        lblDate_dashboard.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDate_dashboard.setText("Date");

        lblTime_dashboard.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTime_dashboard.setText("Time");

        jLabel19.setText("Available Seat :");

        btnRefresh_dashboard.setText("Refresh");
        btnRefresh_dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefresh_dashboardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(245, 245, 245)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(etTotalSeat_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(btnRefresh_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(lblDate_dashboard))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etAvailableSeat_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblTime_dashboard)))
                        .addGap(133, 133, 133))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDate_dashboard)
                            .addComponent(lblTime_dashboard)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRefresh_dashboard)))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(etTotalSeat_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etAvailableSeat_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Dashboard", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdd_busSchedulingaddBusScheduling(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd_busSchedulingaddBusScheduling

        
        BusScheduling schedule=null;
         try {
             schedule = new BusScheduling();
         } catch (SQLException ex) {
             Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
         }
        schedule.add(etBusId_busScheduling.getText(),
                etBusName_busScheduling.getText(),
                etBusType_busScheduling.getText(),
                etFrom_busScheduling.getText(),
                etTo_busScheduling.getText(),
                etDeparture_busScheduling.getText(),
                etArrival_busScheduling.getText(),
                etTotalSeat_busScheduling.getText(), 
                etavailableSeat_busScheduling.getText(),
                etFare_busScheduling.getText(),
                etDate_busScheduling.getText());
      /*  String s_sql = "insert into busscheduling(bid,bname,btype,bfrom,bto,bdeparturetime,barrival,btotalseat,bavailable,bfare,bdate) values(?,?,?,?,?,?,?,?,?,?,?)";

        try {
            pst = conn.prepareStatement(s_sql);
            pst.setString(1, etBusId_busScheduling.getText());
            pst.setString(2, etBusName_busScheduling.getText());
            pst.setString(3, etBusType_busScheduling.getText());
            pst.setString(4, etFrom_busScheduling.getText());
            pst.setString(5, etTo_busScheduling.getText());
            pst.setString(6, etDeparture_busScheduling.getText());
            pst.setString(7, etArrival_busScheduling.getText());
            pst.setString(8, etTotalSeat_busScheduling.getText());
            pst.setString(9, etavailableSeat_busScheduling.getText());
            pst.setString(10, etFare_busScheduling.getText());
            pst.setString(11, etDate_busScheduling.getText());

            pst.execute();

            JOptionPane.showMessageDialog(null, "Schedule Added");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }*/
    }//GEN-LAST:event_btnAdd_busSchedulingaddBusScheduling

    private void btnDelete_busSchedulingdeleteBusSchedule(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete_busSchedulingdeleteBusSchedule

         try {
             BusScheduling schedule = new BusScheduling();
             schedule.delete(etBusId_busScheduling.getText());
             
             
             
             /*
             //String sql = "select * from busscheduling where bid= ?";
             
             // try {
             //   pst = conn.prepareStatement(sql);
             // String s_busId = etBusId_busScheduling.getText();
             //int i_busId = Integer.parseInt(s_busId);
             
             //            pst.setInt(1, i_busId);
             //          rs = pst.executeQuery();
             
             String sql = "select * from busscheduling where bid= ?";
             String s_busId = etBusId_busScheduling.getText();
             
             int i_busId = Integer.parseInt(s_busId);
             
             try {
             pst = conn.prepareStatement(sql);
             pst.setInt(1,i_busId);
             rs = pst.executeQuery();
             
             if(rs.next()){
             String s1 = "delete from busscheduling where bid=" + i_busId;
             pst2 = conn.prepareStatement(s1);
             
             pst2.execute();
             
             JOptionPane.showMessageDialog(null, "Schedule deleted");
             
             }else if(!rs.next()){
             JOptionPane.showMessageDialog(null, "No record found!");
             }
             
             ///  String s_busId = etBusId_busScheduling.getText();
             
             /// int i_busId = Integer.parseInt(s_busId);
             
             }
             
             catch (Exception e) {
             JOptionPane.showMessageDialog(null, e);
             }
             */
         } catch (SQLException ex) {
             Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_btnDelete_busSchedulingdeleteBusSchedule

    private void btnSearch_busSchedulingsearchBusSchedule(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch_busSchedulingsearchBusSchedule

        
      
        
        String sql = "select * from busscheduling where bid= ?";

        try {
            pst = conn.prepareStatement(sql);
            String s_busId = etBusId_busScheduling.getText();
            int i_busId = Integer.parseInt(s_busId);

            pst.setInt(1, i_busId);
            rs = pst.executeQuery();

            // Statement stmt = conn.createStatement();
            //rs = stmt.executeQuery(sql);
            if (rs.next()) {

                /* String name = rs.getString("bname");
                String type = rs.getString("btype");
                String from = rs.getString("bfrom");
                String to = rs.getString("bto");
                String departure = rs.getString("bdeparturetime");
                String arrival = rs.getString("barrival");
                String totalseat = rs.getInt("btotalseat") + "";
                String available = rs.getInt("bavailable") + "";
                String fare = rs.getDouble("bfare") + "";
                String date = rs.getString("bdate");*/

                etBusName_busScheduling.setText(rs.getString("bname"));
                etBusType_busScheduling.setText(rs.getString("btype"));
                etFrom_busScheduling.setText(rs.getString("bfrom"));
                etTo_busScheduling.setText(rs.getString("bto"));
                etDeparture_busScheduling.setText(rs.getString("bdeparturetime"));
                etArrival_busScheduling.setText(rs.getString("barrival"));
                etTotalSeat_busScheduling.setText(rs.getInt("btotalseat") + "");
                etavailableSeat_busScheduling.setText(rs.getInt("bavailable") + "");
                etFare_busScheduling.setText(rs.getDouble("bfare") + "");
                etDate_busScheduling.setText(rs.getString("bdate"));

                JOptionPane.showMessageDialog(null, "search successful");

            }else if(!rs.next()){
                JOptionPane.showMessageDialog(null, "No record found!");
            }

            //pst.execute();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        

    }//GEN-LAST:event_btnSearch_busSchedulingsearchBusSchedule

    private void btnModify_busSchedulingmodifyBusSchedule(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModify_busSchedulingmodifyBusSchedule
       
          BusScheduling schedule=null;
         try {
             schedule = new BusScheduling();
         } catch (SQLException ex) {
             Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
         }
        schedule.modify(etBusId_busScheduling.getText(),
                etBusName_busScheduling.getText(),
                etBusType_busScheduling.getText(),
                etFrom_busScheduling.getText(),
                etTo_busScheduling.getText(),
                etDeparture_busScheduling.getText(),
                etArrival_busScheduling.getText(),
                etTotalSeat_busScheduling.getText(), 
                etavailableSeat_busScheduling.getText(),
                etFare_busScheduling.getText(),
                etDate_busScheduling.getText());
       
        /*
        String s_busId = etBusId_busScheduling.getText();

        int i_busId = Integer.parseInt(s_busId);
        String s_sql = "update busscheduling set bname=?,btype=?,bfrom=?,bto=?,bdeparturetime=?,barrival=?,btotalseat=?,bavailable=?,bfare=?,bdate=? where bid=" + i_busId;

        try {
            pst = conn.prepareStatement(s_sql);

            pst.setString(1, etBusName_busScheduling.getText());
            pst.setString(2, etBusType_busScheduling.getText());
            pst.setString(3, etFrom_busScheduling.getText());
            pst.setString(4, etTo_busScheduling.getText());
            pst.setString(5, etDeparture_busScheduling.getText());
            pst.setString(6, etArrival_busScheduling.getText());
            pst.setString(7, etTotalSeat_busScheduling.getText());
            pst.setString(8, etavailableSeat_busScheduling.getText());
            pst.setString(9, etFare_busScheduling.getText());
            pst.setString(10, etDate_busScheduling.getText());

            pst.execute();

            JOptionPane.showMessageDialog(null, "Schedule Modified");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        */
    }//GEN-LAST:event_btnModify_busSchedulingmodifyBusSchedule

    private void btnClear_busSchedulingclearBusSchedule(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear_busSchedulingclearBusSchedule
        // TODO add your handling code here:

        etBusId_busScheduling.setText("");
        etBusName_busScheduling.setText("");
        etBusType_busScheduling.setText("");
        etFrom_busScheduling.setText("");
        etTo_busScheduling.setText("");
        etDeparture_busScheduling.setText("");
        etArrival_busScheduling.setText("");
        etTotalSeat_busScheduling.setText("");
        etavailableSeat_busScheduling.setText("");
        etFare_busScheduling.setText("");
        etDate_busScheduling.setText("");
    }//GEN-LAST:event_btnClear_busSchedulingclearBusSchedule

    private void etBusName_busSchedulingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etBusName_busSchedulingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etBusName_busSchedulingActionPerformed

    private void btnRefresh_dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefresh_dashboardActionPerformed
        // TODO add your handling code here:
        updateTable();
    }//GEN-LAST:event_btnRefresh_dashboardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Admin().setVisible(true);
            }
        });
         
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd_busScheduling;
    private javax.swing.JButton btnClear_busScheduling;
    private javax.swing.JButton btnDelete_busScheduling;
    private javax.swing.JButton btnModify_busScheduling;
    private javax.swing.JButton btnRefresh_dashboard;
    private javax.swing.JButton btnSearch_busScheduling;
    private javax.swing.JTextField etArrival_busScheduling;
    private javax.swing.JTextField etAvailableSeat_dashboard;
    private javax.swing.JTextField etBusId_busScheduling;
    private javax.swing.JTextField etBusName_busScheduling;
    private javax.swing.JTextField etBusType_busScheduling;
    private javax.swing.JTextField etDate_busScheduling;
    private javax.swing.JTextField etDeparture_busScheduling;
    private javax.swing.JTextField etFare_busScheduling;
    private javax.swing.JTextField etFrom_busScheduling;
    private javax.swing.JTextField etTo_busScheduling;
    private javax.swing.JTextField etTotalSeat_busScheduling;
    private javax.swing.JTextField etTotalSeat_dashboard;
    private javax.swing.JTextField etavailableSeat_busScheduling;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblDate_dashboard;
    private javax.swing.JLabel lblTime_dashboard;
    private javax.swing.JTable tblBooking_Dashboard;
    private javax.swing.JTable tblBusInfo_dashboard;
    // End of variables declaration//GEN-END:variables
}
