/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package busticketbooking;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class BusScheduling extends javax.swing.JFrame {

    Connection conn;
    ResultSet rs;
    PreparedStatement pst, pst2;

    public BusScheduling() throws SQLException {
        super("Bus Scheduling");
        initComponents();
        conn = JavaConnect.ConnecrDb();
        //AutoIncr();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    /*  public void AutoIncr(){
        int i=0;
        jTextField1.setText(""+i.nextInt(1000+1));
    }*/
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        etBusId_busScheduling = new javax.swing.JTextField();
        etBusName_busScheduling = new javax.swing.JTextField();
        etFrom_busScheduling = new javax.swing.JTextField();
        etTo_busScheduling = new javax.swing.JTextField();
        etDeparture_busScheduling = new javax.swing.JTextField();
        etArrival_busScheduling = new javax.swing.JTextField();
        etTotalSeat_busScheduling = new javax.swing.JTextField();
        etavailableSeat_busScheduling = new javax.swing.JTextField();
        etFare_busScheduling = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        etBusType_busScheduling = new javax.swing.JTextField();
        btnAdd_busScheduling = new javax.swing.JButton();
        btnDelete_busScheduling = new javax.swing.JButton();
        btnModify_busScheduling = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        etDate_busScheduling = new javax.swing.JTextField();
        btnClear_busScheduling = new javax.swing.JButton();
        btnSearch_busScheduling = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bus Id : ");

        jLabel2.setText("Bus Name :");

        jLabel3.setText("Bus Type  :");

        jLabel4.setText("From  :");

        jLabel6.setText("Departure :");

        jLabel7.setText("Arrival :");

        jLabel8.setText("Total Seat :");

        jLabel9.setText("Available Seat :");

        jLabel10.setText("Fare  :");

        etBusName_busScheduling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etBusName_busSchedulingActionPerformed(evt);
            }
        });

        jLabel11.setText("To     :");

        btnAdd_busScheduling.setText("Add");
        btnAdd_busScheduling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBusScheduling(evt);
            }
        });

        btnDelete_busScheduling.setText("Delete");
        btnDelete_busScheduling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBusSchedule(evt);
            }
        });

        btnModify_busScheduling.setText("Modify");
        btnModify_busScheduling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyBusSchedule(evt);
            }
        });

        jLabel12.setText("Date");

        btnClear_busScheduling.setText("Clear");
        btnClear_busScheduling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBusSchedule(evt);
            }
        });

        btnSearch_busScheduling.setText("Search");
        btnSearch_busScheduling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBusSchedule(evt);
            }
        });

        jLabel13.setText("Bus Scheduling");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10)
                        .addComponent(jLabel11)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd_busScheduling)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(btnDelete_busScheduling)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etBusName_busScheduling, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etBusId_busScheduling, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(etDate_busScheduling, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(etTo_busScheduling, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(etArrival_busScheduling, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(etavailableSeat_busScheduling, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(etFare_busScheduling, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                        .addComponent(etTotalSeat_busScheduling, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(etDeparture_busScheduling, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(etFrom_busScheduling, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(etBusType_busScheduling, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSearch_busScheduling, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModify_busScheduling)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClear_busScheduling)))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(etBusId_busScheduling, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(etBusName_busScheduling, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(etBusType_busScheduling, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etFrom_busScheduling, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etTo_busScheduling, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(etDeparture_busScheduling, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(etArrival_busScheduling, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(etTotalSeat_busScheduling, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(etavailableSeat_busScheduling, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(etFare_busScheduling, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(etDate_busScheduling, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd_busScheduling)
                    .addComponent(btnDelete_busScheduling)
                    .addComponent(btnModify_busScheduling)
                    .addComponent(btnClear_busScheduling)
                    .addComponent(btnSearch_busScheduling))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void etBusName_busSchedulingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etBusName_busSchedulingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etBusName_busSchedulingActionPerformed

    private void modifyBusSchedule(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyBusSchedule
        String s_busId = etBusId_busScheduling.getText();

        int i_busId = Integer.parseInt(s_busId);
        String s_sql = "update busscheduling set bname=?,btype=?,bfrom=?,bto=?,bdeparturetime=?,barrival=?,btotalseat=?,bavailable=?,bfare=?,bdate=? where bid=" + i_busId;

        try {
            pst = conn.prepareStatement(s_sql);

            pst.setString(1, etBusName_busScheduling.getText());
            pst.setString(2, etBusType_busScheduling.getText());
            pst.setString(3, etFrom_busScheduling.getText());
            pst.setString(4, etTo_busScheduling.getText());
            pst.setString(5, etDeparture_busScheduling.getText());
            pst.setString(6, etArrival_busScheduling.getText());
            pst.setString(7, etTotalSeat_busScheduling.getText());
            pst.setString(8, etavailableSeat_busScheduling.getText());
            pst.setString(9, etFare_busScheduling.getText());
            pst.setString(10, etDate_busScheduling.getText());

            pst.execute();

            JOptionPane.showMessageDialog(null, "Schedule Modified");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_modifyBusSchedule

    private void addBusScheduling(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBusScheduling

        String s_sql = "insert into busscheduling(bid,bname,btype,bfrom,bto,bdeparturetime,barrival,btotalseat,bavailable,bfare,bdate) values(?,?,?,?,?,?,?,?,?,?,?)";

        try {
            pst = conn.prepareStatement(s_sql);
            pst.setString(1, etBusId_busScheduling.getText());
            pst.setString(2, etBusName_busScheduling.getText());
            pst.setString(3, etBusType_busScheduling.getText());
            pst.setString(4, etFrom_busScheduling.getText());
            pst.setString(5, etTo_busScheduling.getText());
            pst.setString(6, etDeparture_busScheduling.getText());
            pst.setString(7, etArrival_busScheduling.getText());
            pst.setString(8, etTotalSeat_busScheduling.getText());
            pst.setString(9, etavailableSeat_busScheduling.getText());
            pst.setString(10, etFare_busScheduling.getText());
            pst.setString(11, etDate_busScheduling.getText());

            pst.execute();

            JOptionPane.showMessageDialog(null, "Schedule Added");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_addBusScheduling

    private void deleteBusSchedule(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBusSchedule

        /*
        String sql = "select * from busscheduling where bid= ?";

        try {
            pst = conn.prepareStatement(sql);
            String s_busId = etBusId_busScheduling.getText();
            int i_busId = Integer.parseInt(s_busId);

            pst.setInt(1, i_busId);
            rs = pst.executeQuery();
        */
        String sql = "select * from busscheduling where bid= ?";
         String s_busId = etBusId_busScheduling.getText();

            int i_busId = Integer.parseInt(s_busId);
        
        try {
            pst = conn.prepareStatement(sql);
            pst.setInt(1,i_busId);
            rs = pst.executeQuery();
            
            if(rs.next()){
            String s1 = "delete from busscheduling where bid=" + i_busId;
            pst2 = conn.prepareStatement(s1);


            pst2.execute();
            

            JOptionPane.showMessageDialog(null, "Schedule deleted");
                
            }else if(!rs.next()){
                JOptionPane.showMessageDialog(null, "No record found!");
            }
            
            
            
          ///  String s_busId = etBusId_busScheduling.getText();

           /// int i_busId = Integer.parseInt(s_busId);
            

        }
            
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }


    }//GEN-LAST:event_deleteBusSchedule

    private void clearBusSchedule(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBusSchedule
        // TODO add your handling code here:

        etBusId_busScheduling.setText("");
        etBusName_busScheduling.setText("");
        etBusType_busScheduling.setText("");
        etFrom_busScheduling.setText("");
        etTo_busScheduling.setText("");
        etDeparture_busScheduling.setText("");
        etArrival_busScheduling.setText("");
        etTotalSeat_busScheduling.setText("");
        etavailableSeat_busScheduling.setText("");
        etFare_busScheduling.setText("");
        etDate_busScheduling.setText("");
    }//GEN-LAST:event_clearBusSchedule

    private void searchBusSchedule(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBusSchedule

        String sql = "select * from busscheduling where bid= ?";

        try {
            pst = conn.prepareStatement(sql);
            String s_busId = etBusId_busScheduling.getText();
            int i_busId = Integer.parseInt(s_busId);

            pst.setInt(1, i_busId);
            rs = pst.executeQuery();

            // Statement stmt = conn.createStatement();
            //rs = stmt.executeQuery(sql);
            if (rs.next()) {

               /* String name = rs.getString("bname");
                String type = rs.getString("btype");
                String from = rs.getString("bfrom");
                String to = rs.getString("bto");
                String departure = rs.getString("bdeparturetime");
                String arrival = rs.getString("barrival");
                String totalseat = rs.getInt("btotalseat") + "";
                String available = rs.getInt("bavailable") + "";
                String fare = rs.getDouble("bfare") + "";
                String date = rs.getString("bdate");*/

                etBusName_busScheduling.setText(rs.getString("bname"));
                etBusType_busScheduling.setText(rs.getString("btype"));
                etFrom_busScheduling.setText(rs.getString("bfrom"));
                etTo_busScheduling.setText(rs.getString("bto"));
                etDeparture_busScheduling.setText(rs.getString("bdeparturetime"));
                etArrival_busScheduling.setText(rs.getString("barrival"));
                etTotalSeat_busScheduling.setText(rs.getInt("btotalseat") + "");
                etavailableSeat_busScheduling.setText(rs.getInt("bavailable") + "");
                etFare_busScheduling.setText(rs.getDouble("bfare") + "");
                etDate_busScheduling.setText(rs.getString("bdate"));
                
                JOptionPane.showMessageDialog(null, "search successful");

            }else if(!rs.next()){
                JOptionPane.showMessageDialog(null, "No record found!");
            }

            //pst.execute();

            

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }


    }//GEN-LAST:event_searchBusSchedule

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusScheduling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusScheduling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusScheduling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusScheduling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new BusScheduling().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(BusScheduling.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd_busScheduling;
    private javax.swing.JButton btnClear_busScheduling;
    private javax.swing.JButton btnDelete_busScheduling;
    private javax.swing.JButton btnModify_busScheduling;
    private javax.swing.JButton btnSearch_busScheduling;
    private javax.swing.JTextField etArrival_busScheduling;
    private javax.swing.JTextField etBusId_busScheduling;
    private javax.swing.JTextField etBusName_busScheduling;
    private javax.swing.JTextField etBusType_busScheduling;
    private javax.swing.JTextField etDate_busScheduling;
    private javax.swing.JTextField etDeparture_busScheduling;
    private javax.swing.JTextField etFare_busScheduling;
    private javax.swing.JTextField etFrom_busScheduling;
    private javax.swing.JTextField etTo_busScheduling;
    private javax.swing.JTextField etTotalSeat_busScheduling;
    private javax.swing.JTextField etavailableSeat_busScheduling;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
