/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package busticketbooking;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Dristy
 */
public class CheckingForReservation extends javax.swing.JFrame {

    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    String s_busId;

        public  String s_busName;
        public    String s_busType;
        public    String s_fromRoute;
        public    String s_toRoute;
        public    String s_date;
        public    String s_time;
    
    /**
     * Creates new form SeatReservation
     *
     * @throws java.sql.SQLException
     */
    public CheckingForReservation() throws SQLException {
        super("Checking For Reservation");
        initComponents();
        conn = JavaConnect.ConnecrDb();
    }

    public CheckingForReservation(String comboboxSelectBus_booking, String comboboxBusType_booking, String comboboxFrom_booking, String comboboxTo_booking, String etDate_booking, String etTime_booking) {
        s_busName = comboboxSelectBus_booking;
        s_busType = comboboxBusType_booking;
        s_fromRoute = comboboxFrom_booking;
        s_toRoute = comboboxTo_booking;
        s_date = etDate_booking;
        s_time = etTime_booking;
    }
    
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void submit() throws SQLException{
      /* String sql = "select * from BUSSCHEDULING where BNAME=? and BTYPE=? and BFROM=? and BTO=? and BDATE=? and BDEPARTURE=?";
        try {
            pst = conn.prepareStatement(sql);
            String s_busName = (String) comboboxSelectBus_booking.getSelectedItem();
            String s_busType = (String) comboboxBusType_booking.getSelectedItem();
            String s_fromRoute = (String) comboboxFrom_booking.getSelectedItem();
            String s_toRoute = (String) comboboxTo_booking.getSelectedItem();
            String s_date = etDate_booking.getText();
            String s_time = etTime_booking.getText();
            // Checking date and time format
            boolean b_isDate = false;
            boolean b_isTime1 = false;
            boolean b_isTime2 = false;
            String datePattern = "\\d{1,2}-\\d{1,2}-\\d{4}";
            String timePattern1 = "\\d{1,2}:\\d{1,2}am";
            String timePattern2 = "\\d{1,2}:\\d{1,2}pm";
            b_isDate = s_date.matches(datePattern);
            if (b_isDate == false) {
                JOptionPane.showMessageDialog(null, "Date in wrong format");
            }
            b_isTime1 = s_time.matches(timePattern1);
            b_isTime2 = s_time.matches(timePattern2);
            if ((b_isTime1 == false) && (b_isTime2 == false)) {
                JOptionPane.showMessageDialog(null, "Time in wrong format");
            }
            pst.setString(1, s_busName);
            pst.setString(2, s_busType);
            pst.setString(3, s_fromRoute);
            pst.setString(4, s_toRoute);
            pst.setString(5, s_date);
            pst.setString(6, s_time);
            rs = pst.executeQuery();

            //if bus available , pass data of busId to SeatReservation class and go to that class form
            SeatReservation seat = null;
            String s_availableSeat;//= rs.getString("BAVAILABLE");
            int i_availableSeat;// = Integer.parseInt(s_availableSeat);

            if (rs.next()) {

                s_busId = rs.getString("BID");
                s_availableSeat = rs.getString("BAVAILABLE");
                i_availableSeat = Integer.parseInt(s_availableSeat);
                if (i_availableSeat != 0) {
                    setVisible(false);
                    seat = new SeatReservation();
                    seat.setBusId(s_busId);
                    seat.setVisible(true);
                    rs.close();
                    pst.close();
                } else {
                    JOptionPane.showMessageDialog(null, "Seat not available to book");
                }

            } else {
                JOptionPane.showMessageDialog(null, "There is no bus available");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                rs.close();
                pst.close();
            } catch (SQLException e) {
                System.out.println(e);
            }
        }
        */

    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        comboboxTo_booking = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Select Bus");

        jLabel3.setText("From");

        jLabel4.setText("To");

        jLabel5.setText("Date");

        jLabel6.setText("Time");

        comboboxTo_booking.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Destination", "Dhaka", "Khulna", "Vola", "Feni" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(67, 67, 67)
                .addComponent(comboboxTo_booking, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addGap(84, 84, 84)
                .addComponent(jLabel3)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboboxTo_booking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jLabel5)
                .addGap(33, 33, 33)
                .addComponent(jLabel6)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckingForReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckingForReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckingForReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckingForReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CheckingForReservation().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(CheckingForReservation.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }


    // Variables declaration - do not modify                     
    private javax.swing.JComboBox<String> comboboxTo_booking;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration                   
}
